EgiTrails/Controllers/TuristasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EgiTrails.Data;
using EgiTrails.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace EgiTrails.Controllers
{
    public class TuristasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public TuristasController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Turistas
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["telemovelSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Telemovel" : "";
            ViewData["nifSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Nif" : "";
            ViewData["CurrentFilter"] = searchString;

            var turista = from s in _context.Turista
                           select s;


            switch (sortOrder)
            {
                case "telemovel":
                    turista = turista.OrderBy(s => s.Telemovel);
                    break;
                case "Nif":
                    turista = turista.OrderBy(s => s.NIF);
                    break;
                case "email":
                    turista = turista.OrderBy(s => s.Email);
                    break;
                default:
                    turista = turista.OrderBy(s => s.Nome);
                    break;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                turista = turista.Where(s => s.Nome.Contains(searchString)
                                       || s.Telemovel.ToString().Contains(searchString)
                                       || s.Email.Contains(searchString)
                                       || s.NIF.ToString().Contains(searchString));
            }

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            int pageSize = 4;
            return View(await PaginatedList<Turista>.CreateAsync(turista.AsNoTracking(), pageNumber ?? 1, pageSize));

        }

        // GET: Turistas/Details/5
        [Authorize(Roles = "Admin,Guia")]    
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turista = await _context.Turista
                .FirstOrDefaultAsync(m => m.turistaId == id);
            if (turista == null)
            {
                return NotFound();
            }

            return View(turista);
        }

        // GET: Turistas/Create
        public IActionResult Registar()
        {
            return View();
        }

        // POST: Turistas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registar(Registarturista turista)
        {
            if (ModelState.IsValid)
            {
                return View(turista);
            }
            string username = turista.Email;
            IdentityUser user = await _userManager.FindByNameAsync(username);

            if (user != null)
            {
                ModelState.AddModelError("Email", "There is allready a turist with that email.");
                return View(turista);
            }

            user = new IdentityUser(username);
            await _userManager.CreateAsync(user, turista.Password);
            await _userManager.AddToRoleAsync(user, "Turista");

            Turista turistaa = new Turista
            {
                Nome = turista.Nome,
                Email = turista.Email,
                NIF = turista.NIF,
                Telemovel = turista.Telemovel
            };
            _context.Add(turistaa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Home");
        }
        [Authorize(Roles = "Turista")]
        public async Task<IActionResult> EditPersonal()
        {
            string email = User.Identity.Name;

            var turista = await _context.Turista.SingleOrDefaultAsync(c => c.Email == email);
            if (turista == null)
            {
                return NotFound();
            }

            editlogin turistainfo = new editlogin
            {
                Nome = turista.Nome,
                Email = turista.Email,
                NIF = turista.NIF,
                Telemovel = turista.Telemovel
            };

            return View(turistainfo);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPersonal(editlogin turista)
        {
            if (!ModelState.IsValid)
            {
                return View(turista);
            }

            string email = User.Identity.Name;

            var turistaLoggedin = await _context.Turista.SingleOrDefaultAsync(c => c.Email == email);
            if (turistaLoggedin == null)
            {
                return NotFound();
            }

            turistaLoggedin.Nome = turista.Nome;
            turistaLoggedin.Telemovel = turista.Telemovel;
            turistaLoggedin.NIF = turista.NIF;

            try
            {
                _context.Update(turistaLoggedin);
                _context.Update(turistaLoggedin);
                _context.Update(turistaLoggedin);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                //todo: show error message

                throw;
            }
            return RedirectToAction(nameof(Index), "Home");
        }

        // GET: Turistas/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turista = await _context.Turista.FindAsync(id);
            if (turista == null)
            {
                return NotFound();
            }
            return View(turista);
        }

        // POST: Turistas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("turistaId,Nome,Telemovel,Nfi,Email")] Turista turista)
        {
            if (id != turista.turistaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(turista);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TuristaExists(turista.turistaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(turista);
        }

        // GET: Turistas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turista = await _context.Turista
                .FirstOrDefaultAsync(m => m.turistaId == id);
            if (turista == null)
            {
                return NotFound();
            }

            return View(turista);
        }

        // POST: Turistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var turista = await _context.Turista.FindAsync(id);
            _context.Turista.Remove(turista);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TuristaExists(int id)
        {
            return _context.Turista.Any(e => e.turistaId == id);
        }
    }
}

EgiTrails/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EgiTrails</title>
    <link rel="stylesheet" href="~/assets/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/assets/css/style.css" />
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>EgiTrails</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Mamba - v2.4.1
    * Template URL: https://bootstrapmade.com/mamba-one-page-bootstrap-template-free/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>

    <!-- ======= Header ======= -->
    <header id="header">
        <div class="container">

            <div class="logo float-left">
                <!-- <h1 class="text-light"><a href="index.html"><span>EgiTrails</span></a></h1> -->
                <!-- Uncomment below if you prefer to use an image logo -->
                <a href="/#"><img src="assets/img/1.PNG" alt="" class="img-fluid"></a>
            </div>

            <nav class="nav-menu float-right d-none d-lg-block">
                <ul>
                    <li><a href="/#">Home</a></li>
                    <li><a href="/Reservas/Create">Efetuar Reserva</a></li>
                    <li><a href="/Home/PontosInteresse">Pontos de Interesse</a></li>
                    <li><a href="/ListaTrilhos/Index">Trilhos</a></li>
                    <li><a href="/ReservasVeiculos/Index">Veículos</a></li>

                    @if (User.IsInRole("Admin"))
                    {
                        <li><a href="/AprovarTrilhos/Index">Aprovar</a></li>
                    }

                    @if (User.IsInRole("Admin") || User.IsInRole("Guia"))
                    {
                        <li><a asp-action="Index" asp-controller="Turistas">Contas</a></li>
                    }@if (User.IsInRole("Turista"))
                    {
                        <li><a asp-action="EditPersonal" asp-controller="Turistas">Perfil</a></li>
                    }

                    @if (User.IsInRole("Admin") || User.IsInRole("Guia"))
                    {
                        <li class="drop-down">
                            <a href="">BD</a>
                            <ul>
                                <li><a href="/Reservas">ReservaBD</a></li>
                                <li><a href="/Trilhos">TrilhosBD</a></li>
                                <li><a href="/Veiculos">VeiculosBD</a></li>
                            </ul>
                        </li>
                    }
                    <li class="drop-down">
                        <a href="">Sobre</a>
                        <ul>
                            <li><a href="/#team">Equipa</a></li>
                            <li><a href="/#contact">Contactos</a></li>
                            <li><a href="/Home/Sobre">Sobre Nós</a></li>
                        </ul>
                    </li>
                    <li><a href="/Home/COVID19">COVID-19</a></li>
                    <li>
                        <partial name="_LoginPartial" />

                    </li>
                </ul>
</nav><!-- .nav-menu -->

        </div>
    </header><!-- End Header -->


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-info">
                        <h3>EgiTrails</h3>
                        <p>
                            Av. Dr. Francisco Sá Carneiro 50 <br>
                            Guarda, Portugal<br><br>
                            <strong>Telefone:</strong> +351 271 456 789<br>
                            <strong>Email:</strong> egitrails6300@gmail.com<br>
                        </p>
                        <div class="social-links mt-3">
                            <a href="https://www.facebook.com/" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="https://www.instagram.com" class="instagram"><i class="bx bxl-instagram"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Ligações Úteis</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="/#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="/Home/Sobre">Sobre Nós</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Serviços</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="/Home/PoliticaDePrivacidade">Política de Privacidade</a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>EgiTrails</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mamba-one-page-bootstrap-template-free/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->


    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/jquery-sticky/jquery.sticky.js"></script>
    <script src="~/assets/vendor/venobox/venobox.min.js"></script>
    <script src="~/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/assets/vendor/counterup/counterup.min.js"></script>
    <script src="~/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>